spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.24.8.46:3306/lin945?useUnicode=true&characterEncoding=utf-8
    password: 147258369aa..
    username: lin945
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

logging:
  file:
    path: log
  level:
    root: warn
    com.lin: debug
server:
  port: 8080
