spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    password:
    username:
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

logging:
  file:
    path: log
  level:
    root: warn
    com.lin: debug
server:
  port: 8080
